### PR TITLE
feat: cache choices

### LINKED ISSUE #76: Is there any way to make this faster; there is a noticable startup delay

### LINKED ISSUE #77: Cache package per executable
I'll probably implement this myself, I'm making an issue so I don't forget. It's probably also a good practice or something. Suggestions on what other features there should be are welcome.

Features:
- [ ] Cache the package used per executable (this avoids both the nix-index lookup and the selection menu)
- [ ] Add a flag to empty the cache / remove a specific executable

### PR DESCRIPTION
**Pull request by diniamo**
I chose bitcode because it scored the highest on the https://github.com/djkoloski/rust_serialization_benchmark, and doesn't have any dependencies.

Rust makes me unsure about everything, so feel free to point anything out. The worst part is probably that there are 3 checks for whether the cache is available in main, but it's either that or some unreadable nesting.

I probably didn't test enough either, so I'd appreciate some help with that as well.

Closes #77 
Closes #76 
Partly completes #69

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Should we add an option to ignore the cache for one command and update the result? This would be useful if you choose a wrong result for a command.

**Comment by diniamo** [comment]
The remove one already does that, since execution doesn't end after the removal.

**Comment by diniamo** [comment]
I realized that the previous approach was complicated and annoying to use, for example, you would have had to type `, -d hello hello` to overwrite the cache entry for hello. Instead of 1, there are now 2 options, 1 for emptying the entire cache, and 1 for deleting the command from the cache before running the rest of the application logic.

**Comment by diniamo** [comment]
@Artturin not sure if you missed, but I think most people would like to see this merged. Any chance you could take a look?

**Comment by Artturin** [comment]
Awesome, thank you.

**Pull request merged**
