### PR TITLE
remove prebuilt cache

### PR DESCRIPTION
**Pull request by Artturin**
it increases the closure size and limits the system we support
in the future we can implement this better in the script

### CODE REVIEW

**Comment by DavHau** [comment]
I think the builtin index DB is quite useful and increases the UX of comma a lot as users can just install and use the tool without extra steps that involve learning about the nix-index tool etc.

We could just allow the builtin index to be `null` and set it `null` whenever it's not available for a system.

**Comment by Artturin** [comment]
The builtin index should be handled outside of nix in the script because it is quite large

**Comment by DavHau** [comment]
> The builtin index should be handled outside of nix in the script because it is quite large

Sounds like a good idea. I think this should be implemented by the current PR. Then we won't lose that feature.

**Comment by Artturin** [comment]
i merged this now so he users who couldn't install comma now can install it

i'll start working on implementing it in the script now

**Comment by Artturin** [comment]
actually, that feature should be implemented in [nix-index](https://github.com/bennofs/nix-index) itself

**Comment by DavHau** [comment]
> actually, that feature should be implemented in [nix-index](https://github.com/bennofs/nix-index) itself

I'm not sure if I would agree. But if you think so, you should be the one who makes sure that this feature is implemented in `nix-index` **before** you remove that feature here. Next time it would be nice if you would check what others think about it, before deciding about such change.

Why do I think this feature is important?
One power comma gives you is to just use the tools you're used to on another machine which doesn't have your environment.
Earlier you could just do a `nix shell nixpkgs#comma` and have a fully featured comma quickly.

This capability is now broken through that PR.

**Pull request merged**
